#!/bin/bash

#shellcheck disable=SC2317,SC1091,SC2120,SC2034

# DIRECTORY DEFINITIONS
export FFMPEG_KIT_TMPDIR="${BASEDIR}/.tmp"

export MINGW_W64_BRANCH="master"
export BINUTILS_BRANCH="binutils-2_44-branch"
export GCC_BRANCH="releases/gcc-14"
export LOG_FILE="${BASEDIR}"/build.log

export sandbox="prebuilt"
export WORKDIR="$BASEDIR/$sandbox"
export SCRIPTDIR="$BASEDIR/scripts"

# variables with their defaults
export build_force="0"
export build_ffmpeg_static=n
export build_ffmpeg_shared=y
export build_ffmpeg_kit_only=n
export build_dvbtee=n
export build_libmxf=n
export build_mp4box=n
export build_mplayer=n
export build_vlc=n
export build_lsw=n # To build x264 with L-Smash-Works.
export build_dependencies=y
export git_get_latest=y
export prefer_stable=y # Only for x264 and x265.
export build_amd_amf=y
export ffmpeg_git_checkout_version="release/8.0"
export build_ismindex=n
export enable_gpl=y
export original_cflags="$CFLAGS"
export build_x264_with_libav=n # To build x264 with Libavformat.
export ffmpeg_git_checkout="https://github.com/FFmpeg/FFmpeg.git"
export cpu_count=$(nproc)
export original_cpu_count=$(nproc) # save it away for some that revert it temporarily
export PKG_CONFIG_LIBDIR= # disable pkg-config from finding [and using] normal linux system installed libs [yikes]
export original_path=$PATH

export BUILD_STEPS=(
"build_dlfcn" \
"build_libxavs" \
"build_libdavs2" \
"build_libxavs2" \
"build_mingw_std_threads" \
"build_zlib" \
"build_libcaca" \
"build_bzlib" \
"build_lzma" \
"build_iconv" \
"build_sdl2" \
"build_amf" \
"build_libvpl" \
"build_nvenc" \
"build_cuvid" \
"build_libzimg" \
"build_libopenjpeg" \
"build_opengl" \
"build_libpng" \
"build_libwebp" \
"build_libxml2" \
"build_brotli" \
"build_libfreetype" \
"build_libharfbuzz" \
"build_libvmaf" \
"build_libfontconfig" \
"build_gmp" \
"build_libnettle" \
"build_unistring" \
"build_libidn2" \
"build_zstd" \
"build_openssl" \
"build_gnutls" \
"build_curl" \
"build_libogg" \
"build_libvorbis" \
"build_libopus" \
"build_libspeexdsp" \
"build_libspeex" \
"build_libtheora" \
"build_libgsm" \
"build_mpg123" \
"build_libmp3lame" \
"build_libtwolame" \
"build_libopenmpt" \
"build_libopencore_amrnb" \
"build_libvo_amrwbenc" \
"build_libilbc" \
"build_libmodplug" \
"build_libgme" \
"build_libbluray" \
"build_libbs2b" \
"build_libsoxr" \
"build_libflite" \
"build_libsnappy" \
"build_vamp_plugin" \
"build_fftw" \
"build_chromaprint" \
"build_libsamplerate" \
"build_librubberband" \
"build_frei0r" \
"build_svt_hevc" \
"build_svt_vp9" \
"build_libsvtav1" \
"build_libvidstab" \
"build_libmysofa" \
"build_decklink" \
"build_libzvbi" \
"build_libfribidi" \
"build_libass" \
"build_libxvid" \
"build_libsrt" \
"build_libaribcaption" \
"build_libaribb24" \
"build_libtesseract" \
"build_liblensfun" \
"build_libtensorflow" \
"build_libvpx" \
"build_libx265" \
"build_libopenh264" \
"build_libaom" \
"build_libdav1d" \
"build_vulkan" \
"build_libplacebo" \
"build_libshaderc" \
"build_avisynth" \
"build_libvvenc" \
"build_libvvdec" \
"build_libx264" \
"build_libjsoncpp" \
"build_libcodec2" \
"build_libjxl" \
"build_libkvazaar" \
"build_libxeve" \
"build_libxevd" \
"build_ladspa" \
"build_libfdk_aac" \
"build_libshine" \
"build_openal" \
"build_pocketsphinx" \
"build_whisper" \
"build_lcms2" \
"build_liblc3" \
"build_liblcevc_dec" \
"build_liboapv" \
"build_libqrencode" \
"build_libuavs3d" \
"build_vapoursynth" \
"build_libquirc" \
"build_librsvg" \
"build_libopencv" \
"build_librav1e" \
"build_gcrypt" \
"build_librist" \
"build_lv2" \
"build_libcdio" \
"build_libpulse" \
"build_librtmp" \
"build_librabbitmq" \
"build_libssh" \
"build_libtls" \
"build_libzmq" \
"build_mbedtls" \
"build_opencl" \
"build_libglslang" \
"build_libklvanc" \
"build_vulkan_static" \
"build_libnpp" \
"build_cuda_nvcc" \
"build_libjack" \
"build_alsa" \
"build_libdc1394" \
"build_libdrm" \
"build_libiec61883" \
"build_libv4l2" \
"build_libxcb" \
"build_libxcb_shape" \
"build_libxcb_shm" \
"build_libxcb_xfixes" \
"build_rkmpp" \
"build_vaapi" \
"build_xlib" \
"build_libmfx" \
"build_omx" \
"build_sndio" \
"build_libdvdnav" \
"build_libdvdread" \
"build_libopenvino")
